redirects:
    ai/using-predicthq-with-ai-assistants: ai/grounding-llms-in-real-world-data.md
    integrations/third-party-integrations/google-cloud-bigquery: integrations/integration-guides/loading-event-data-into-a-data-warehouse.md
    integrations/third-party-integrations/integrate-with-a-demand-forecast-in-powerbi: getting-started/guides/features-api-guides/integrate-with-a-demand-forecast-in-powerbi.md
    integrations/third-party-integrations/tableau-data-connector: integrations/third-party-integrations/using-event-data-in-tableau.md
    getting-started/core-concepts/industry-tuned-predictions: getting-started/guides/industry-specific-event-filters.md
    getting-started/guides/how-industry-affects-results: getting-started/guides/industry-specific-event-filters.md
    getting-started/guides/guide-to-protecting-predicthq-data: getting-started/core-concepts/guide-to-protecting-predicthq-data.md
    getting-started/guides/tutorials: getting-started/guides/README.md
    getting-started/guides/tutorials/filtering-and-finding-relevant-events: getting-started/guides/events-api-guides/filtering-and-finding-relevant-events.md
    getting-started/guides/tutorials/displaying-events-in-a-heatmap-calendar: getting-started/guides/events-api-guides/displaying-events-in-a-heatmap-calendar.md
    getting-started/guides/tutorials/displaying-events-on-a-map: getting-started/guides/events-api-guides/displaying-events-on-a-map.md
    getting-started/guides/tutorials/improving-demand-forecasting-models-with-event-features: getting-started/guides/features-api-guides/improving-demand-forecasting-models-with-event-features.md
    getting-started/guides/tutorials/using-event-data-in-power-bi: integrations/third-party-integrations/using-event-data-in-power-bi.md
    getting-started/guides/tutorials/using-event-data-in-tableau: integrations/third-party-integrations/using-event-data-in-tableau.md
    getting-started/guides/tutorials/connecting-to-predicthq-apis-with-microsoft-excel: integrations/third-party-integrations/connecting-to-predicthq-apis-with-microsoft-excel.md
    getting-started/guides/tutorials/loading-event-data-into-a-data-warehouse: integrations/integration-guides/loading-event-data-into-a-data-warehouse.md
    categoryinfo/attended-events: getting-started/predicthq-data/event-categories/attendance-based-events.md
    categoryinfo/general-category-information: getting-started/predicthq-data/event-categories/README.md
    categoryinfo/general-info: getting-started/predicthq-data/event-categories/README.md
    categoryinfo/introduction: getting-started/predicthq-data/event-categories/README.md
    categoryinfo/live-tv-events: getting-started/predicthq-data/event-categories/live-tv-events.md
    categoryinfo/non-attended-events: getting-started/predicthq-data/event-categories/non-attendance-based-events.md
    categoryinfo/predicted-end-time: getting-started/predicthq-data/predicted-end-times.md
    categoryinfo/unscheduled-events: getting-started/predicthq-data/event-categories/unscheduled-events.md
    datascience/academic-events-part1: getting-started/guides/events-api-guides/academic-events-data-science-guides.md
    datascience/academic-events-part2: getting-started/guides/events-api-guides/academic-events-data-science-guides.md
    datascience/academic-events-part3: getting-started/guides/events-api-guides/academic-events-data-science-guides.md
    datascience/academic-events: getting-started/guides/events-api-guides/academic-events-data-science-guides.md
    datascience/attended-events-part1: getting-started/guides/events-api-guides/attendance-based-events-data-science-guides.md
    datascience/attended-events-part2: getting-started/guides/events-api-guides/attendance-based-events-data-science-guides.md
    datascience/attended-events-part3: getting-started/guides/events-api-guides/attendance-based-events-data-science-guides.md
    datascience/attended-events: getting-started/guides/events-api-guides/attendance-based-events-data-science-guides.md
    datascience/beam-api-guide: getting-started/guides/beam-guides/README.md
    datascience/correlation: getting-started/guides/beam-guides/README.md
    datascience/demand-forecasting: getting-started/guides/features-api-guides/demand-forecasting-data-science-guides.md
    datascience/demand-surge-notebook: getting-started/guides/features-api-guides/README.md
    datascience/demandforecasting: getting-started/guides/features-api-guides/demand-forecasting-data-science-guides.md
    datascience/example-notebooks: getting-started/guides/events-api-guides/working-with-venues.md
    datascience/faq: getting-started/guides/events-api-guides/README.md
    datascience/feature-engineering-guide: getting-started/guides/features-api-guides/feature-engineering-guide.md
    datascience/features-api-usage: getting-started/guides/features-api-guides/README.md
    datascience/features-api: getting-started/guides/features-api-guides/README.md
    datascience/gettingstarted: getting-started/guides/features-api-guides/README.md
    datascience/introduction: getting-started/data-science-notebooks.md
    datascience/live-tv-events-part1: getting-started/guides/live-tv-event-guides/live-tv-events-data-science-guides.md
    datascience/live-tv-events-part2: getting-started/guides/live-tv-event-guides/live-tv-events-data-science-guides.md
    datascience/live-tv-events-part3: getting-started/guides/live-tv-event-guides/live-tv-events-data-science-guides.md
    datascience/live-tv-events: getting-started/guides/live-tv-event-guides/README.md
    datascience/non-attended-events-part1: getting-started/guides/events-api-guides/non-attendance-based-events-data-science-guides.md
    datascience/non-attended-events-part2: getting-started/guides/events-api-guides/non-attendance-based-events-data-science-guides.md
    datascience/non-attended-events-part3: getting-started/guides/events-api-guides/non-attendance-based-events-data-science-guides.md
    datascience/non-attended-events: getting-started/guides/events-api-guides/non-attendance-based-events-data-science-guides.md
    datascience/severe-weather-events-part1: getting-started/guides/events-api-guides/severe-weather-events-data-science-guides.md
    datascience/severe-weather-events-part2: getting-started/guides/events-api-guides/severe-weather-events-data-science-guides.md
    datascience/severe-weather-events-part3: getting-started/guides/events-api-guides/severe-weather-events-data-science-guides.md
    datascience/severe-weather-events: getting-started/guides/events-api-guides/severe-weather-events-data-science-guides.md
    getting-started/guides/use-case-guides: getting-started/use-case-guides/README.md
    getting-started/guides/use-case-guides/accommodation-the-proven-path-to-value: getting-started/use-case-guides/accommodation-the-proven-path-to-value.md
    getting-started/tutorials-by-use-case: getting-started/how-to-use-predicthq.md
    getting-started/tutorials-by-use-case/automated-demand-forecasting-with-ml-models: getting-started/guides/features-api-guides/improving-demand-forecasting-models-with-event-features.md
    getting-started/tutorials-by-use-case/dynamic-pricing: getting-started/how-to-use-predicthq.md
    getting-started/tutorials-by-use-case/inventory-management: getting-started/how-to-use-predicthq.md
    getting-started/tutorials-by-use-case/workforce-optimization: getting-started/how-to-use-predicthq.md
    getting-started/tutorials-by-use-case/visualization-and-insights: getting-started/how-to-use-predicthq.md
    guides/adx: integrations/third-party-integrations/aws-data-exchange/README.md
    guides/api-quickstart: getting-started/api-quickstart.md
    guides/event-categories: getting-started/predicthq-data/event-categories/README.md
    guides/features-api: getting-started/guides/features-api-guides/README.md
    guides/geo-info-and-polygons: getting-started/guides/geolocation-guides/overview.md
    guides/live-tv-events: getting-started/guides/live-tv-event-guides/README.md
    guides/locations: getting-started/guides/geolocation-guides/README.md
    guides/loop-links-integration-guide: integrations/integration-guides/integrate-with-loop-links.md
    guides/multi-day-and-umbrella-events: getting-started/guides/date-and-time-guides/working-with-multi-day-and-umbrella-events.md
    guides/predicted-end-times: getting-started/predicthq-data/predicted-end-times.md
    guides/predicthq-ranks: getting-started/predicthq-data/ranks/README.md
    guides/quickstart: getting-started/api-quickstart.md
    guides/recurring-events: getting-started/guides/date-and-time-guides/working-with-recurring-events.md
    guides/relevance: getting-started/core-concepts/what-is-beam.md
    guides/snowflake: integrations/third-party-integrations/snowflake/README.md
    guides/staying-updated: integrations/integration-guides/keep-data-updated-via-api.md
    guides/using-placekey-with-poi-data: getting-started/guides/geolocation-guides/join-events-using-placekey.md
    guides/using-the-apis-with-location-based-access: getting-started/guides/geolocation-guides/searching-by-location/working-with-location-based-subscriptions.md
    sdks/javascript: sdks/javascript-sdk.md
    sdks/python: sdks/python-sdk.md
    start/adx: integrations/third-party-integrations/aws-data-exchange/README.md
    start/aei: getting-started/guides/features-api-guides/README.md
    start/api-quickstart: getting-started/api-quickstart.md
    start/categories: getting-started/predicthq-data/event-categories/README.md
    start/features-api: getting-started/guides/features-api-guides/README.md
    start/live-tv-events-api: getting-started/guides/live-tv-event-guides/README.md
    start/live-tv-events: getting-started/guides/live-tv-event-guides/README.md
    start/locations: getting-started/guides/geolocation-guides/README.md
    start/predicthq-ranks: getting-started/predicthq-data/ranks/README.md
    start/ranks: getting-started/predicthq-data/ranks/README.md
    start/snowflake: integrations/third-party-integrations/snowflake/README.md
    start/staying-updated: integrations/integration-guides/keep-data-updated-via-api.md
    start/updating: integrations/integration-guides/keep-data-updated-via-api.md
    tools/data-exporter: integrations/third-party-integrations/README.md
    tools/tableau-connector: integrations/third-party-integrations/using-event-data-in-tableau.md
