redirects:
    api/api-changes: predicthq-api/overview/api-changes.md
    api/attribution: predicthq-api/overview/attribution.md
    api/authenticating: predicthq-api/overview/authenticating.md
    api/changes: predicthq-api/overview/api-changes.md
    api/errors: predicthq-api/overview/troubleshooting.md
    api/introduction: predicthq-api/overview/README.md
    api/rate-limits: predicthq-api/overview/rate-limits.md
    api/requests: predicthq-api/overview/README.md
    api/responses: predicthq-api/overview/README.md
    categoryinfo/attended-events: getting-started/predicthq-data/event-categories/attendance-based-events.md
    categoryinfo/general-category-information: getting-started/predicthq-data/event-categories/README.md
    categoryinfo/general-info: getting-started/predicthq-data/event-categories/README.md
    categoryinfo/introduction: getting-started/predicthq-data/event-categories/README.md
    categoryinfo/live-tv-events: getting-started/predicthq-data/event-categories/live-tv-events.md
    categoryinfo/non-attended-events: getting-started/predicthq-data/event-categories/non-attendance-based-events.md
    categoryinfo/predicted-end-time: getting-started/predicthq-data/predicted-end-times.md
    categoryinfo/unscheduled-events: getting-started/predicthq-data/event-categories/unscheduled-events.md
    datascience/academic-events-part1: getting-started/guides/events-api-guides/academic-events-data-science-guides.md
    datascience/academic-events-part2: getting-started/guides/events-api-guides/academic-events-data-science-guides.md
    datascience/academic-events-part3: getting-started/guides/events-api-guides/academic-events-data-science-guides.md
    datascience/academic-events: getting-started/guides/events-api-guides/academic-events-data-science-guides.md
    datascience/attended-events-part1: getting-started/guides/events-api-guides/attendance-based-events-data-science-guides.md
    datascience/attended-events-part2: getting-started/guides/events-api-guides/attendance-based-events-data-science-guides.md
    datascience/attended-events-part3: getting-started/guides/events-api-guides/attendance-based-events-data-science-guides.md
    datascience/attended-events: getting-started/guides/events-api-guides/attendance-based-events-data-science-guides.md
    datascience/beam-api-guide: getting-started/guides/beam-guides/README.md
    datascience/correlation: getting-started/guides/beam-guides/README.md
    datascience/demand-forecasting: getting-started/guides/features-api-guides/demand-forecasting-data-science-guides.md
    datascience/demand-surge-notebook: getting-started/guides/features-api-guides/README.md
    datascience/demandforecasting: getting-started/guides/features-api-guides/demand-forecasting-data-science-guides.md
    datascience/example-notebooks: getting-started/guides/events-api-guides/working-with-venues.md
    datascience/faq: getting-started/guides/events-api-guides/README.md
    datascience/feature-engineering-guide: getting-started/guides/features-api-guides/feature-engineering-guide.md
    datascience/features-api-usage: getting-started/guides/features-api-guides/README.md
    datascience/features-api: getting-started/guides/features-api-guides/README.md
    datascience/gettingstarted: getting-started/guides/features-api-guides/README.md
    datascience/introduction: getting-started/guides/events-api-guides/README.md
    datascience/live-tv-events-part1: getting-started/guides/live-tv-event-guides/live-tv-events-data-science-guides.md
    datascience/live-tv-events-part2: getting-started/guides/live-tv-event-guides/live-tv-events-data-science-guides.md
    datascience/live-tv-events-part3: getting-started/guides/live-tv-event-guides/live-tv-events-data-science-guides.md
    datascience/live-tv-events: getting-started/guides/live-tv-event-guides/README.md
    datascience/non-attended-events-part1: getting-started/guides/events-api-guides/non-attendance-based-events-data-science-guides.md
    datascience/non-attended-events-part2: getting-started/guides/events-api-guides/non-attendance-based-events-data-science-guides.md
    datascience/non-attended-events-part3: getting-started/guides/events-api-guides/non-attendance-based-events-data-science-guides.md
    datascience/non-attended-events: getting-started/guides/events-api-guides/non-attendance-based-events-data-science-guides.md
    datascience/severe-weather-events-part1: getting-started/guides/events-api-guides/severe-weather-events-data-science-guides.md
    datascience/severe-weather-events-part2: getting-started/guides/events-api-guides/severe-weather-events-data-science-guides.md
    datascience/severe-weather-events-part3: getting-started/guides/events-api-guides/severe-weather-events-data-science-guides.md
    datascience/severe-weather-events: getting-started/guides/events-api-guides/severe-weather-events-data-science-guides.md
    guides/adx: predicthq-api/bulk-data-delivery/aws-data-exchange.md
    guides/api-quickstart: getting-started/api-quickstart.md
    guides/event-categories: getting-started/predicthq-data/event-categories.md
    guides/features-api: getting-started/guides/features-api-guides/README.md
    guides/geo-info-and-polygons: getting-started/guides/geolocation-guides/overview.md
    guides/live-tv-events: getting-started/guides/live-tv-event-guides/README.md
    guides/locations: getting-started/guides/geolocation-guides.md
    guides/loop-links-integration-guide: getting-started/guides/integrate-with-loop-links.md
    guides/multi-day-and-umbrella-events: getting-started/guides/date-and-time-guides/working-with-multi-day-and-umbrella-events.md
    guides/predicted-end-times: getting-started/predicthq-data/predicted-end-times.md
    guides/predicthq-ranks: getting-started/predicthq-data/ranks.md
    guides/quickstart: getting-started/api-quickstart.md
    guides/recurring-events: getting-started/guides/date-and-time-guides/working-with-recurring-events.md
    guides/relevance: getting-started/guides/understanding-relevance-field-in-event-results.md
    guides/snowflake: predicthq-api/bulk-data-delivery/snowflake.md
    guides/staying-updated: predicthq-api/bulk-data-delivery/keep-data-updated-via-api.md
    guides/using-placekey-with-poi-data: getting-started/guides/geolocation-guides/join-events-using-placekey.md
    guides/using-the-apis-with-location-based-access: getting-started/guides/geolocation-guides/searching-by-location/working-with-location-based-subscriptions.md
    oauth2: predicthq-api/overview/authenticating.md
    oauth2/errors: predicthq-api/overview/troubleshooting.md
    oauth2/introduction: predicthq-api/overview/authenticating.md
    resources/beam: api/beam/search-analyses.md
    resources/broadcasts: api/broadcasts/search-broadcasts.md
    resources/demand-surge: api/demand-surge/get-demand-surges.md
    resources/events: api/events/search-events.md
    resources/features: api/features/get-features.md
    resources/loop: api/loop/loop-links/search-loop-links.md
    resources/places: api/places/search-places.md
    resources/saved-locations-api: api/saved-locations/README.md
    resources/saved-locations: api/saved-locations/search-saved-locations.md
    resources/suggested-radius: api/suggested-radius/get-suggested-radius.md
    sdks/javascript: predicthq-api/sdks/javascript-sdk.md
    sdks/python: predicthq-api/sdks/python-sdk.md
    start/adx: predicthq-api/bulk-data-delivery/aws-data-exchange.md
    start/aei: getting-started/guides/features-api-guides/README.md
    start/api-quickstart: getting-started/api-quickstart.md
    start/categories: getting-started/predicthq-data/event-categories/README.md
    start/features-api: getting-started/guides/features-api-guides/README.md
    start/live-tv-events-api: getting-started/guides/live-tv-event-guides/README.md
    start/live-tv-events: getting-started/guides/live-tv-event-guides/README.md
    start/locations: getting-started/guides/geolocation-guides/README.md
    start/predicthq-ranks: getting-started/predicthq-data/ranks/README.md
    start/ranks: getting-started/predicthq-data/ranks/README.md
    start/snowflake: predicthq-api/bulk-data-delivery/snowflake.md
    start/staying-updated: predicthq-api/bulk-data-delivery/keep-data-updated-via-api.md
    start/updating: predicthq-api/bulk-data-delivery/keep-data-updated-via-api.md
    tools/data-exporter: predicthq-api/bulk-data-delivery/export-data-via-control-center.md
    tools/tableau-connector: tools/tableau-data-connector.md
