name: Fetch Labels


on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: install python dependencies
        run: pip install requests python-dotenv

      - name: run script to fetch labels
        run: python3 scripts/fetch-labels.py
        env:
          PHQ_API_TOKEN: ${{ secrets.PHQ_API_TOKEN }}

      - name: Commit and push if data changed
        run: |-
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Fetched latest labels" || exit 0
          git push

      